### ISSUE TITLE
auth errors

### ISSUE THREAD

**Issue by n0vedad** [ericvolp12/go-bsky-feed-generator#1]
Try to get up running your feed-generator but run into some errors:

`Message from server: Failed to get claims from auth header: Failed to parse authorization token: Failed to parse public key from decoded multibase key: invalid pub key length 35`

maybe you can help me?

**Comment by jazware** [comment]
Hey, I ended up rewriting the auth module a few weeks ago (updated version can be found [here](https://github.com/ericvolp12/bsky-experiments/blob/main/pkg/auth/auth.go)) and haven't copied those changes over into this repo yet. I might take a crack at moving those into this repo tomorrow, thanks for the heads up!

**Comment by n0vedad** [comment]
Would be really nice if you could bump your updated auth module with all dependencies into this repo. Tried to get this working but run into some errors, I'm sure I've forgot something

**Comment by jazware** [comment]
Think I've got it up to date now, wanna give it a shot?

**Comment by n0vedad** [comment]
Thank you for your effort! But that issues still persists.

`Message from server: Failed to get claims from auth header: Failed to parse authorization token: wrong key type`

**Comment by n0vedad** [comment]
now it's working thank you!
